clouds:
  - name: varinha
    points:
      - [0.0, 0.0, 0.0]
      - [0.1010, 0.0, 0.0]
      - [0.0, 0.1505, 0.0]
  - name: create3
    points:
      - [-0.086, 0.096, 0.0]
      - [0.012, 0.132, 0.0]
      - [0.12, -0.048, 0.0]

  - name: wave_rover_1
    points:
      - [0.008, -0.018, 0.0]
      - [-0.041, 0.021, 0.0]
      - [0.048, 0.019, 0.0]

  - name: wave_rover_2
    points:
      - [0.0, 0.0, 0.0]
      - [1.0, 1.0, 0.0]
      - [2.0, 0.0, 0.0]
