clouds:
  - name: create3
    points:
      - [0.0, 0.0, 0.0]
      - [1.0, 0.0, 0.0]
      - [1.0, 1.0, 0.0]
      - [0.0, 1.0, 0.0]

  - name: wave_rover_1
    points:
      - [0.0, 0.0, 0.0]
      - [0.0, 1.0, 0.0]
      - [0.0, 2.0, 0.0]
      - [1.0, 0.0, 0.0]

  - name: wave_rover_2
    points:
      - [0.0, 0.0, 0.0]
      - [1.0, 1.0, 0.0]
      - [2.0, 0.0, 0.0]
