clouds:
  - name: varinha
    points:
      - [0.0, 0.0, 0.0]
      - [0.1010, 0.0, 0.0]
      - [0.0, 0.1505, 0.0]

  - name: create3
    points:
      - [0.0, 0.0, 0.0]
      - [0.132, 0.055, 0.0]
      - [0.209, -0.044, 0.0]

  - name: waverover1
    points:
      - [0.0, 0.0, 0.0]
      - [0.10, 0, 0.0]
      - [0.0, 0.075, 0.0]

  - name: waverover2
    points:
      - [0.0, 0.0, 0.0]
      - [10.0, 0, 0.0]
      - [0.0, 7.5, 0.0]

  - name: gopigo4
    points:
      - [0.0, 0.0, 0.0]
      - [0.112, 0.0, 0.0]
      - [0.041, -0.047, 0.0]